//
//  TablesNames.swift
//  Bonocle_Spelling
//
//  Created by Mahmoud ELDemery on 24/06/2021.
//

import Foundation
let tables_names_map: [String : String] = [
    "as.tbl" : "Assamese braille",
    "bh.tbl" : "Bihari braille",
    "lt.tbl" : "Lithuanian 8-dot braille",
    "da-dk-g28.ctb" : "Danish 8-dot fully contracted braille",
    "de-g0.utb" : "German uncontracted braille",
    "te.tbl" : "Telugu braille",
    "tr.tbl" : "Turkish computer braille",
    "ur-pk-g1.utb" : "Urdu uncontracted braille",
    "ar-ar-g2 2.ctb" : "Arabic contracted braille",
    "en-gb-comp8.ctb" : "U.K. English computer braille",
    "fi-fi-8dot.ctb" : "Finnish computer braille",
    "ar.tbl" : "Arabic uncontracted braille",
    "haw-us-g1.ctb" : "Hawaiian braille",
    "ar-ar-g2.ctb" : "Arabic contracted braille",
    "kru.tbl" : "Kurukh braille",
    "en_US-comp8-ext.tbl" : "U.S. English (EBAE) 8-dot computer braille",
    "da-dk-g16.ctb" : "Danish 6-dot uncontracted braille",
    "lv.tbl" : "Latvian braille",
    "mr.tbl" : "Marathi braille",
    "cy.tbl" : "Welsh contracted braille",
    "fi.utb" : "Finnish braille",
    "bn.tbl" : "Bengali braille",
    "ta-ta-g1.ctb" : "Tamil braille",
    "hu-hu-g2.ctb" : "Hungarian fully contracted braille",
    "es-g2.ctb" : "Spanish contracted braille",
    "da-dk-g26l-lit.ctb" : "Danish 6-dot partially contracted braille",
    "ur-pk-g2.ctb" : "Urdu contracted braille",
    "ru-compbrl.ctb" : "Russian computer braille",
    "de-g2.ctb" : "German fully contracted braille",
    "nl.tbl" : "Dutch braille as used in the Netherlands",
    "sv-1996.ctb" : "Swedish computer braille (1996 standard)",
    "no-no-comp8.ctb" : "Norwegian computer braille",
    "bo.tbl" : "Tibetan computer braille",
    "da-dk-g26-lit.ctb" : "Danish 6-dot fully contracted braille",
    "fr-bfu-comp8.utb" : "Unified French 8 dots braille",
    "ga-g1.utb" : "Irish uncontracted braille",
    "de-g1.ctb" : "German partially contracted braille",
    "de-de-comp8.ctb" : "German 8 dot computer braille",
    "ta.tbl" : "Tamil computer braille",
    "vi.tbl" : "Vietnamese braille",
    "nl_BE.tbl" : "Dutch braille as used in Belgium",
    "mt.tbl" : "Maltese computer braille",
    "no.tbl" : "Norwegian grade 3 contracted braille",
    "eo.tbl" : "Esperanto braille",
    "mao-nz-g1.ctb" : "Maori braille",
    "da-dk-g26l.ctb" : "Danish 6-dot partially contracted braille",
    "hu-hu-comp8.ctb" : "Hungarian computer braille",
    "fa-ir-g1.utb" : "Persian braille",
    "hi.tbl" : "Hindi braille",
    "gd.tbl" : "Scottish Gaelic computer braille",
    "it-it-comp8.utb" : "Italian computer braille",
    "el.tbl" : "Greek braille",
    "sa.tbl" : "Sanskrit braille",
    "sv.tbl" : "Swedish braille",
    "gr-bb.ctb" : "Ancient Greek braille",
    "kok.tbl" : "Konkani braille",
    "pl.tbl" : "Polish braille",
    "uk.utb" : "Ukrainian braille",
    "mni.tbl" : "Manipuri braille",
    "ga.tbl" : "Irish contracted braille",
    "hy.tbl" : "Armenian computer braille",
    "zhcn-g1.ctb" : "Mainland Chinese braille with tone",
    "sd.tbl" : "Sindhi braille",
    "sr.tbl" : "Serbian braille",
    "pi.tbl" : "Pali braille",
    "gu.tbl" : "Gujarati braille",
    "afr-za-g1.ctb" : "Afrikaans braille",
    "zhcn-g2.ctb" : "Two-cell Chinese Braille",
    "awa.tbl" : "Awadhi braille",
    "en_CA.tbl" : "Canadian English computer braille",
    "ru.tbl" : "Russian braille",
    "no-no-8dot.utb" : "Norwegian 8-dot uncontracted braille",
    "sk.tbl" : "Slovak braille",
    "ro.tbl" : "Romanian computer braille",
    "da-dk-g16-lit.ctb" : "Danish 6-dot uncontracted braille",
    "vi.ctb" : "Vietnamese computer braille",
    "en-ueb-g1.ctb" : "English (UEB) uncontracted braille",
    "en-us-g1.ctb" : "U.S. English (EBAE) uncontracted braille",
    "is.tbl" : "Icelandic braille",
    "fi.tbl" : "Finnish computer braille",
    "kn.tbl" : "Kannada braille",
    "hu.tbl" : "Hungarian partially contracted braille",
    "cs-comp8.utb" : "Czech computer braille",
    "sl-si-comp8.ctb" : "Slovenian computer braille",
    "hr-comp8.tbl" : "Croatian computer braille",
    "gon.tbl" : "Gondi braille",
    "bra.tbl" : "Braj braille",
    "en-ueb-g2.ctb" : "English (UEB) contracted braille",
    "es.tbl" : "Spanish uncontracted braille",
    "mn-MN-g2.ctb" : "Mongolian contracted braille",
    "da-dk-g28l.ctb" : "Danish 8-dot partially contracted braille",
    "mun.tbl" : "Munda braille",
    "it.tbl" : "Italian braille",
    "pt-pt-comp8.ctb" : "Portuguese computer braille",
    "eo-g1-x-system.ctb" : "Esperanto x-system braille",
    "ko-2006-g2.ctb" : "Korean contracted braille (2006 standard)",
    "pa.tbl" : "Punjabi braille",
    "chr-us-g1.ctb" : "Cherokee braille",
    "zh_TW.tbl" : "Taiwanese braille",
    "sl.tbl" : "Slovenian braille",
    "pl-pl-comp8.ctb" : "Polish computer braille",
    "et.tbl" : "Estonian computer braille",
    "mwr.tbl" : "Marwari braille",
    "afr-za-g1 2.ctb" : "Afrikaans braille",
    "ko-2006-g1.ctb" : "Korean uncontracted braille (2006 standard)",
    "lt-6dot.tbl" : "Lithuanian braille",
    "en_US.tbl" : "U.S. English (EBAE) contracted braille",
    "Es-Es-G0.utb" : "Spanish computer braille",
    "zh_CHN.tbl" : "Mainland Chinese braille without tone",
    "mn-MN-g1.utb" : "Mongolian uncontracted braille",
    "pt.tbl" : "Portuguese contracted braille",
    "fa-ir-comp8.ctb" : "Persian computer braille",
    "dra.tbl" : "Dravidian computer braille",
    "he.tbl" : "Hebrew computer braille",
    "ckb.tbl" : "Kurdish braille",
    "gez.tbl" : "Ethiopic braille",
    "hr-g1.tbl" : "Croatian braille",
    "zh_HK.tbl" : "Cantonese braille",
    "da-dk-g08.ctb" : "Danish computer braille",
    "ko-g2.ctb" : "Korean contracted braille",
    "fr-bfu-g2.ctb" : "Unified French contracted braille",
    "cs.tbl" : "Czech braille",
    "no-no-g0.utb" : "Norwegian 6-dot uncontracted braille",
    "pt-pt-g1.utb" : "Portuguese uncontracted braille",
    "or.tbl" : "Oriya braille",
    "ar-ar-comp8.utb" : "Arabic computer braille",
    "fr-bfu-comp6.utb" : "Unified French 6 dots braille",
    "en-gb-g1.utb" : "U.K. English uncontracted braille",
    "ml.tbl" : "Malayalam braille",
    "ko-g1.ctb" : "Korean uncontracted braille",
    "bg.tbl" : "Bulgarian computer braille",
    "kha.tbl" : "Khasi braille",
    "iu-ca-g1.ctb" : "Inuktitut braille",
    "no-no-g1.ctb" : "Norwegian grade 1 contracted braille",
    "cy-cy-g1.utb" : "Welsh uncontracted braille",
    "no-no-8dot-fallback-6dot-g0.utb" : "Norwegian 8-dot uncontracted braille with 6-dot fallback",
    "da-dk-g26.ctb" : "Danish 6-dot fully contracted braille",
    "ne.tbl" : "Nepali braille",
    "sv-1989.ctb" : "Swedish computer braille (1989 standard)",
    "da-dk-g18.ctb" : "Danish 8-dot uncontracted braille",
    "en_GB.tbl" : "U.K. English contracted braille",
    "no-no-g2.ctb" : "Norwegian grade 2 contracted braille",
    "ca.tbl" : "Catalan braille",
    "en-us-comp6.ctb" : "U.S. English (EBAE) 6-dot computer braille",
    "tr-g2.tbl" : "Turkish Braille Code (Grade 1)"
]
